# Generated by Django 6.0.7 on 2026-09-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_leave_leavebalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
