# Generated by Django 6.0.7 on 2026-09-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_department_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
