# Generated by Django 6.0.7 on 2026-09-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_holiday_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='holiday_type',
            field=models.CharField(choices=[('Festival', 'Festival'), ('National', 'National Holiday'), ('Public', 'Public Holiday'), ('Optional', 'Optional Holiday')], default='Festival', max_length=20),
        ),
        migrations.AddField(
            model_name='holiday',
            name='state',
            field=models.CharField(default='Andhra Pradesh', max_length=50),
        ),
    ]
